recipe-it/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/**
 * test route.
 */
Route::get('/test', function () {
    return 'Hi! It is a test page';
})->name('testRoute');

/**
 * re-direct route with page parameter, this route allows to change pages in project.
 */
Route::get('/redirect/{pageName}', 'RedirectController@redirectPage')->where('pageName','[A-Za-z]+');

Route::resource('phoneBook','Recipe\PhonebookController');

Route::get('/cancel', function() {
    return redirect()->route('phoneBook.index')->with('cancel','Cancel Action!');

})->name('cancel');

Route::get('/phonebook/{id}/confirm','Recipe\PhonebookController@confirm' )->name('phoneBook.confirm');

recipe-it/app/Models/Phonebook.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Phonebook extends Model
{
    //
}

recipe-it/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

recipe-it/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

recipe-it/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

recipe-it/app/Http/Controllers/Recipe/PhonebookController.php
<?php

namespace App\Http\Controllers\Recipe;

use App\Http\Controllers\Controller;
use App\Models\Phonebook;
use Illuminate\Http\Request;

class PhonebookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $phoneBook = Phonebook::paginate(2);
        return view('phonebook.index', compact('phoneBook'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return  view('phonebook.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $phoneBookInstance = new Phonebook;
        $phoneBookInstance->name = $request->name;
        $phoneBookInstance->lastName = $request->lastName;
        $phoneBookInstance->telephone = $request->telephone;
        $phoneBookInstance->gender = $request->gender;
        $phoneBookInstance->role = $request->role;
        $phoneBookInstance->email = $request->email;
        $phoneBookInstance->salary = $request->salary;
        $phoneBookInstance->save();
        return redirect()->route('phoneBook.index')->with('data',"The register implementation is success");
        //return 'The register implementation is success';
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $phoneBook = Phonebook::findOrFail($id);
        $phoneBook->delete();
        return redirect()->route('phoneBook.index')->with('data',"The register was deleting successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function confirm($id)
    {
        $phoneBook = Phonebook::findOrFail($id);
        return view('phonebook.confirm', compact('phoneBook'));
    }
}

recipe-it/app/Http/Controllers/RedirectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

/**
 * Class RedirectController, this controller allows to perform redirect method.
 * @package App\Http\Controllers
 * @author arivadeneria
 */
class RedirectController extends Controller
{
    /**
     * this method allows to redirect to another page in to the project, using identifier id.
     * @param $pageName
     * @return \Illuminate\Http\RedirectResponse
     */
    public function redirectPage($pageName){
        return redirect()->route($pageName);
    }
}

recipe-it/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

recipe-it/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

recipe-it/resources/views/phonebook/confirm.blade.php
@extends('template.baseTemplate')

@section('title','Confirm popup')


@section('content')
    <div class="container py-5">
        <h1>¿Do you want to delete the register {{ $phoneBook->name }} {{ $phoneBook->lastname }}? </h1>

        <form method="post" action="{{ route('phoneBook.destroy', $phoneBook->id )}}">
            @method('DELETE')
            @csrf
            <button type="submit" class="redondo btn btn-danger">
                <i class="fas fa-trash-alt"></i> Delete
            </button>
            <a class="redondo btn btn-secondary" href="{{ route('cancel') }}">
                <i class="fas fa-ban"></i> Cancel
            </a>
        </form>

    </div>


    @include('template.footer',['container'=>'container'])

@endsection

recipe-it/resources/views/phonebook/create.blade.php
@extends('template.baseTemplate')

@section('title','Create')

@section('content')



    <div class="container">
        <br>
        <nav class="navbar navbar-light">
            <a class="navbar-brand"><img id="icono" class="img-responsive"
                                         src="https://imge.apk.tools/300/d/3/1/com.widesoft.guiatelefonica.png"></a>

            <ul class="nav flex-column text-center">
                <li class="nav-item">
                    <span class="nav-link active">Welcome</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">log out</a>
                </li>
            </ul>

        </nav>


        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Library</a></li>
                <li class="breadcrumb-item active" aria-current="page">Data</li>
            </ol>
        </nav>
    </div>

    <form method="POST" action="{{ route('phoneBook.store') }}">
        @csrf
        <div class="container register">


            <div class="row">
                <div class="col-md-3 register-left">
                    <img src="http://www.idaipqroo.org.mx/wp-content/uploads/2018/06/proteccion-de-datos-personales-791x1024.png" alt=""/>
                    <h3>Bienvenid@</h3>
                    <p>Por favor llena los datos correctamente en el sistema!</p>

                </div>
                <div class="col-md-9 register-right">

                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

                            <h3 class="register-heading">Crear nuevo Registro</h3>

                            <div class="row register-form">

                                <div class="col-md-6">

                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text"><i class="fa fa-user text-info"></i></div>
                                            </div>
                                            <input type="text" class="form-control" id="name" name="name" placeholder="Name" required="">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text"><i class="fa fa-user-edit text-info"></i></div>
                                            </div>
                                            <input type="text" class="form-control" id="lastName" name="lastName" placeholder="lastName" required="">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text"><i class="fa fa-phone text-info"></i></div>
                                            </div>
                                            <input class="form-control" type="number" name="telephone" placeholder="telephone: +593 996057105" id="Telephone">
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="maxl">
                                            <label class="radio inline">
                                                <input type="radio" name="gender" value="Male" checked>
                                                <span> Male </span>
                                            </label>
                                            <label class="radio inline">
                                                <input type="radio" name="gender" value="Female">
                                                <span>Female </span>
                                            </label>
                                            <label class="radio inline">
                                                <input type="radio" name="gender" value="GLBTI">
                                                <span>GLBTI </span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">


                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text"><i class="fa  fa-at text-info"></i></div>
                                            </div>
                                            <input type="email" name="email" class="form-control" placeholder="Email" value="" />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text"><i class="fa fa-map-marker-alt text-info"></i></div>
                                            </div>
                                            <select name="role" class="form-control">
                                                <option class="hidden" selected disabled>Role</option>
                                                <option>Chef</option>
                                                <option>Junior chef</option>
                                                <option>Master chef</option>
                                            </select>
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text"><i class="fa  fa-dollar-sign text-info"></i></div>
                                            </div>
                                            <input type="number" class="form-control" name="salary" placeholder="salary *" value="" />
                                        </div>
                                    </div>





                                    <button type="submit" class="redondo btn btn-info"><i class="fas fa-save"></i> Guardar</button>
                                    <a href="{{ route('cancel') }}" class="redondo btn btn-danger"><i class="fas fa-ban"></i> Cancelar</a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>

    </form>


    @include('template.footer',['container'=>'container'])


@endsection

recipe-it/resources/views/phonebook/index.blade.php
@extends('template.baseTemplate')
@section('title','Phone Book')
@section('content')
    <div class="container-fluid registerinicio">
        <div class="row">
            <div class="col-md-6 register-left register-left1">
                <img src="http://www.idaipqroo.org.mx/wp-content/uploads/2018/06/proteccion-de-datos-personales-791x1024.png" alt=""/>
            </div>
            <div class="col-md-6 register-left">

                <h3>Welcome</h3>
                <p>Please complete all of the fields correctly!</p>

            </div>
        </div>
    </div>



    <div class="container-fluid ">
        @if (session('data'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{session('data')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
            @if ( session('cancel')  )
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ session('cancel') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif

        <br>
        <nav class="navbar navbar-light">
            <a class="navbar-brand"><img id="icono" class="img-responsive"
                                         src="https://imge.apk.tools/300/d/3/1/com.widesoft.guiatelefonica.png"></a>

            <ul class="nav flex-column text-center">
                <li class="nav-item">

                </li>
                <li class="nav-item">

                </li>
            </ul>

        </nav>


        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Library</a></li>
                <li class="breadcrumb-item active" aria-current="page">Data</li>
            </ol>
        </nav>

        <br>
        <h1 class="text-center">Phone Book</h1>

        <br>
        <div class="row float-right">
            <a href="{{route('phoneBook.create')}}" class="btn btn-info btncolorblanco"><i class="fas fa-user-plus"></i> Create New Register</a>
        </div>
        <br>
            <div class="col-md-12">
        <table class="table-responsive table text-center col-md-12">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Telephone</th>
                <th scope="col">Gender</th>
                <th scope="col">Email</th>
                <th scope="col">Role</th>
                <th scope="col">Salary</th>
                <th scope="col">Action</th>

            </tr>
            </thead>
            <tbody>
            @foreach($phoneBook as $phoneBookItem)


            <tr>
                <th scope="row">{{ $phoneBookItem->id }}</th>
                <td>{{$phoneBookItem->name}} {{$phoneBookItem->lastName}}</td>
                <td>{{$phoneBookItem->telephone}}</td>
                <td>{{$phoneBookItem->gender}}</td>
                <td>{{$phoneBookItem->email}}</td>
                <td>{{$phoneBookItem->salary}}</td>
                <td>{{$phoneBookItem->role}}</td>
                <td><a class="btn btn-success btncolorblanco">
                        <i class="fa fa-edit"></i> Edit
                    </a>

                    <a href="{{ route('phoneBook.confirm', $phoneBookItem->id) }}" class="btn btn-danger btncolorblanco">
                        <i class="fa fa-trash-alt"></i> Delete
                    </a>
                </td>

            </tr>
            @endforeach
            </tbody>
        </table>
                {{$phoneBook}}
            </div>

    </div>

@include('template.footer', ['container' => 'container-fluid'])
@endsection

recipe-it/resources/views/template/baseTemplate.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- This file has been downloaded from Bootsnipp.com. Enjoy! -->
    <title>  @yield('title','template')  </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">




    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <style type="text/css">

        .registerinicio{
            /*background: -webkit-linear-gradient(left, #3931af, #00c6ff);
            background: -webkit-linear-gradient(left, #020110, #00c6ff);
            background: -webkit-linear-gradient(left,#293437, #00c6ff);*/
            background: -webkit-linear-gradient(left,#3f7483, #0dc9ff);
            margin-top: 3%;
            /*padding: 3%; */
        }

        .register{
            /*background: -webkit-linear-gradient(left, #3931af, #00c6ff);
            background: -webkit-linear-gradient(left, #020110, #00c6ff);
            background: -webkit-linear-gradient(left,#293437, #00c6ff);*/
            background: -webkit-linear-gradient(left,#3f7483, #0dc9ff);
            /*margin-top: 3%;*/
            padding: 3%;
        }

        .register-left{
            text-align: center;
            color: #fff;
            margin-top: 4%;
        }
        .register-left input{
            border: none;
            border-radius: 1.5rem;
            padding: 2%;
            width: 60%;
            background: #f8f9fa;
            font-weight: bold;
            color: #383d41;
            margin-top: 30%;
            margin-bottom: 3%;
            cursor: pointer;
        }
        .register-right{
            background: #f8f9fa;
            border-top-left-radius: 10% 50%;
            border-bottom-left-radius: 10% 50%;
        }
        .register-left img{
            margin-top: 15%;
            margin-bottom: 5%;
            width: 100%;
            -webkit-animation: mover 2s infinite  alternate;
            animation: mover 1s infinite  alternate;
        }

        @-webkit-keyframes mover {
            0% { transform: translateY(0); }
            100% { transform: translateY(-20px); }
        }
        @keyframes mover {
            0% { transform: translateY(0); }
            100% { transform: translateY(-20px); }
        }
        .register-left p{
            font-weight: lighter;
            padding: 12%;
            margin-top: -9%;
        }
        .register .register-form{
            padding: 10%;
            margin-top: 10%;
        }
        .btnRegister{
            float: right;
            margin-top: 10%;
            border: none;
            border-radius: 1.5rem;
            padding: 2%;
            background: #0062cc;
            color: #fff;
            font-weight: 600;
            width: 50%;
            cursor: pointer;
        }
        .register .nav-tabs{
            margin-top: 3%;
            border: none;
            background: #0062cc;
            border-radius: 1.5rem;
            width: 28%;
            float: right;
        }
        .register .nav-tabs .nav-link{
            padding: 2%;
            height: 34px;
            font-weight: 600;
            color: #fff;
            border-top-right-radius: 1.5rem;
            border-bottom-right-radius: 1.5rem;
        }
        .register .nav-tabs .nav-link:hover{
            border: none;
        }
        .register .nav-tabs .nav-link.active{
            width: 100px;
            color: #0062cc;
            border: 2px solid #0062cc;
            border-top-left-radius: 1.5rem;
            border-bottom-left-radius: 1.5rem;
        }
        .register-heading{
            text-align: center;
            margin-top: 8%;
            margin-bottom: -15%;
            color: #495057;
        }


        .register .register-form .form-control {
            /* border-radius: 1rem;*/
        }



        .register-left1 img{
            margin-top: 0;
            margin-bottom: 0%;
            width: 20%;

        }


        .btncolorblanco {
            color: white !important;
            margin: 1px;
        }


        .container-fluid{
            width: 90% !important;
        }



        .fa {
            width: 20px;
        }

        .redondo {
            border-radius: 64px;
        }
        body {
            background-color: #0f8bf41a;
            font-family: 'Underdog', cursive;
        }



        footer {
            left:0px;
            bottom:0px;
            height:30px;
            width:100%;

        }

        .footers a {color:#696969;}
        .footers p {color:#696969;}
        .footers ul {line-height:30px;}
        #social-fb:hover {
            color: #3B5998;
            transition:all .001s;
        }
        #social-tw:hover {
            color: #4099FF;
            transition:all .001s;
        }
        #social-gp:hover {
            color: #d34836;
            transition:all .001s;
        }
        #social-em:hover {
            color: #f39c12;
            transition:all .001s;
        }

        .breadcrumb {
            background-color: #e9ecef00;
        }



        #icono {
            width: 20%;

        }
    </style>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
</head>
<body>

@yield('content')

</body>
</html>